# Be sure to restart your server when you modify this file.
 
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
 
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.
 
# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
 
development:
  secret_key_base: d1fe567a0ee5860f58db1ad6e25922a0a68e59146e2828c77fde4f47eae3dd77534e8e43347f0280d1d5f9c2d053af8c1bc2e47583012ad0881059b9087271bb
 
test:
  secret_key_base: b43b29086554694bd6478f33766336bb765ca591cc30a7d95d6b5388ceb7e4a4d4cb0d48570657303499ef5ccd3c7776d0a40a957eed60d240a4c91a6600b71d
 
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
